### PR TITLE
Fixes https://github.com/stylelint/stylelint/issues/1741

### PR DESCRIPTION
**Pull request by OxyDesign**
That will fix the issue with some pseudo selectors cases with LESS (false indentation issue)

### CODE REVIEW

**Comment by ntwb** [comment]
PR #53 should resolve the Travis CI errors in this PR

**Comment by OxyDesign** [comment]
Thanks. Hope it's going to be merged soon then

**Comment by jdforrester** [comment]
I've merged #54 instead which achieves the same effect.

**Comment by OxyDesign** [comment]
Hi, sure. As long as it's updated with 8.0.0 and the latest release includes it I'm fine with it. Thanks

**Pull request closed without merging**
