### PR TITLE
Support stylelint 11

### PR DESCRIPTION
**Pull request by nwoltman**
~Support latest and future versions of stylelint~

~This way, we won't need to do this song and dance every time a new major version of `stylelint` is released.~

### CODE REVIEW

**Comment by jdforrester** [comment]
This just means this will silently break when upstream breaking changes happen again, which is exactly what we were trying to avoid…

**Comment by nwoltman** [comment]
From looking at the history of this repo, a major change to stylelint has never broken this plugin, so this seemed like a pretty safe change.

Alternatively, perhaps this repo could use a dependency bot to automatically update stylelint and run the tests as soon as new major versions are released.

**Comment by nwoltman** [comment]
Okay, I updated the change to only have stylelint 11 as a peerDependency.

**Comment by jdforrester** [comment]
Sorry! Totally forgot to do this myself. Thank you.

**Pull request merged**
