### PR TITLE
Support stylelint 12

### PR DESCRIPTION
**Pull request by larslaade**
Adding support for stylelint 12.

### CODE REVIEW

**Comment by larslaade** [comment]
Just wondering: why is there not a range for peerDependencies like in [stylelint-scss](https://github.com/kristerkari/stylelint-scss/blob/master/package.json#L47) ?

**Comment by jdforrester** [comment]
> Just wondering: why there isn't a range for peerDependencies like in [stylelint-scss](https://github.com/kristerkari/stylelint-scss/blob/master/package.json#L47) ?

See #79 where this was discussed.

**Comment by axten** [comment]
@jdforrester please release it :)

**Comment by jdforrester** [comment]
> @jdforrester please release it :)

Sorry, was waiting for #82 to land; releasing now. :-)

**Comment by axten** [comment]
thx :)

**Pull request merged**
